@startuml
!$AWS_DARK = true

!define AWSPuml https://raw.githubusercontent.com/awslabs/aws-icons-for-plantuml/v18.0/dist
!include AWSPuml/AWSCommon.puml

!include AWSPuml/AWSSimplified.puml
!include AWSPuml/Groups/AWSCloud.puml
!include AWSPuml/General/Servers.puml
!include AWSPuml/Compute/Lambda.puml
!include AWSPuml/Storage/SimpleStorageService.puml
!include AWSPuml/ApplicationIntegration/EventBridge.puml

title "Overview"
left to right direction

skinparam ArrowThickness 4
skinparam DefaultFontSize 20
skinparam TitleFontSize 30

Servers(opentransportdata, "opentransportdata", "actual data")

AWSCloudGroup(cloud) {
    Lambda(actualDataDownloader, "Actual Data Downloader", "")
    SimpleStorageService(actualDataStorage, "Storage", "")
    EventBridge(eventBridge, "Event Bus", "")
    Lambda(monthlyChartGenerator, "Monthly Chart Generator", "")
    Lambda(dailyChartGenerator, "Daily Chart Generator", "")
    SimpleStorageService(dailyChartStorage, "Storage", "")
    SimpleStorageService(monthlyChartStorage, "Storage", "")

    eventBridge --> actualDataDownloader: 1. Triggers daily
    actualDataDownloader -> actualDataStorage: 3. Saves actual data in
    actualDataStorage -> eventBridge: 4. Creates object created event in

    eventBridge --> dailyChartGenerator: 5. Triggers
    actualDataStorage <-- dailyChartGenerator: 6. Gets actual data from
    dailyChartGenerator --> dailyChartStorage: 7. Saves daily chart in

    eventBridge --> monthlyChartGenerator: 8. Triggers
    actualDataStorage <-- monthlyChartGenerator: 9 Gets actual data from
    monthlyChartGenerator --> monthlyChartStorage: 10. Saves monthly chart in
}

opentransportdata <-- actualDataDownloader: 2. Loads actual data from

@enduml